### ISSUE TITLE
Sa2KB data after version change

### ISSUE THREAD

**Issue by fmele** [AKSW/gerbil#102]
Hi,
I am conducting a study on an annotator and even though I understand the Sa2KB problem has been dropped from the new version, I wonder if there's any chance I can still consult at least the old overview data for the Sa2KB. Would it be possible to obtain a copy of the old db to use in a local installation?
Thank you in advance, and keep up the good work!
Francesco Mele

**Comment by MichaelRoeder** [comment]
Hi  Francesco,

first of all, the Sa2KB has been dropped as a separate Experiment Type. The functionality is integrated into the A2KB task. Thus, if you want to evaluate an annotator and it is adding confidence values to its results, these values are still used like they have been used in an Sa2KB experiment.

The old values are still online. We do not have deleted anything ;-)
However, since the Sa2KB experiment is not present in the overview chart anymore, you have to know the ids of the single experiments in which the numbers have been calculated.

Yes, you can have a copy of the database. Unfortunately, its structure is not that easy to access ;-)
Can you describe which exact numbers you would like to know. Than it is easier to discuss how we can make the numbers available.

Cheers,
Michael

**Comment by fmele** [comment]
Hi Michael,
the values for the A2KB problem on the current version are affected by some problems caused by the new matching procedure (as documented on #98 for the D2KB experiment type) so I can't check the new data against the results obtained in version 1.1.4 and unfortunately I don't have ids for the experiments since I realized the experiment wasn't available anymore when I went ahead and tried to perform one. :)
Anyway I don't plan on inspecting the database by hand, I'd just like to plug it inside my local 1.1.4 installation to look at the old Sa2KB overview data. It would be also ok if you could simply point me towards an experiment page for an Sa2KB experiment with strong matching involving the majority of annotators and datasets (if such an experiment exists in your list of saved ids).

Regards,
Francesco Mele

**Comment by MichaelRoeder** [comment]
Hi Francesco,

there are no real problems with 1.2.1 ;-)
However, I created a [file](http://139.18.2.164/mroeder/gerbil/database_backup_16_11_2015.tgz) containing the current database.

If you want to use the numbers for a publication and need them to be available online, we can manually create an experiment inside the database. However, I would like to avoid this step as long as it is not needed.

Please close this issue if the database works inside your local GERBIL instance.

Cheers,
Michael

**Comment by fmele** [comment]
It worked like a charm! I'm really grateful for your help :)

Regards,
Francesco Mele
