### ISSUE TITLE
about AIDA-Conll dataset

### ISSUE THREAD

**Issue by chabmed** [AKSW/gerbil#118]
Hi, 
i'm working with gerbil in Local, and i"m trying to test my system on AIDA-Conll dataset,i've already got my license for the dataset and i generated AIDA-YAGO2-dataset.tsv, but it's written in the wiki that gerbil need  AIDA-YAGO2-dataset-upadte.tsv, i'm wondering if they are the same i just have to rename the file?
I supposed that they are the same and i worked with them,
but when i see the text input from Gerbil when i run the web service are not like the original text
Supposing we have in a text "in a" but gerbil generate them in one word "ina" and it's caused by the "AIDACoNLLDataset.java" : to insert the whitespace 
/* if ((textBuilder.length() > 0) && (line[TEXT_INDEX].length() > 1)
                                    && (Character.isLetterOrDigit(line[TEXT_INDEX].charAt(0)))) {
                                textBuilder.append(' ');
                            }*/ 
and also supposing we have to a subtext in this form "a (b)" but gerbil generate this "a( b)",
And this affect my results.
maybe i made mistake and AIDA-YAGO2-dataset.tsv and AIDA-YAGO2-dataset-upadte.tsv are not the same.
thanks

**Comment by MichaelRoeder** [comment]
Hi,

we detected this problem, yesterday. The "in a" problem is fixed in the commit 487e13bfe2ea100dfc65d697405bb35debb0d535. The second problem that affects brackets and quotes will be fixed in the next commits. Both will be released with version 1.2.3.

The adapter should work with the `AIDA-YAGO2-dataset.tsv` file as well. I don't know which parts have been updated in the new file but I think that we can determine it.

Cheers,
Michael

**Comment by chabmed** [comment]
Hi,
thank you for your quick reply

**Comment by chabmed** [comment]
Hi, 
i have another question for URI retirever, in AIDACoNLLDataset.java, you are using ANNOTATION_TITLE_INDEX instead of ANNOTATION_URI_INDEX, but the uriS in ANNOTATION_TITLE_INDEX use Unicode encoding and not UTF-8, i saw the details of the uris that exist in the Golstandard. Some examples 
Claude Makelele :: [http://aksw.org/unknown_entity/http___en_wikipedia_org_wiki_Claude_Maku00e9lu00e9lu00e9, http://aksw.org/unknown_entity/http___dbpedia_org_resource_Claude_Maku00e9lu00e9lu00e9]
it returns an errors for every uri that contains a special character even points "." and parenthesis
Barbarians :: [http://aksw.org/unknown_entity/http___dbpedia_org_resource_Barbarian_Fu002eCu002e, http://aksw.org/unknown_entity/http___en_wikipedia_org_wiki_Barbarian_Fu002eCu002e]
And that's why for entity linking the result are not what we expect for all the annotators 
In AIDA-COnll test b contains 5616 uris and 802 among them are "unknown_entity"
Thank you,
Mohamed

**Comment by chabmed** [comment]
i'm actually trying to fix this by replacing
uris = WikipediaHelper.generateUriSet(line[ANNOTATION_TITLE_INDEX]);
with
uris = WikipediaHelper.generateUriSet(java.net.URLDecoder.decode(line[ANNOTATION_TITLE_INDEX]));
and i'll report the results
thank you,
Mohamed

**Comment by MichaelRoeder** [comment]
Hi Mohamed,

I took a look at both versions of the AIDA dataset. The only differences that I could find were the values in the last column. While the `AIDA-YAGO2-dataset.tsv` contains values like `/m/0345h` the `AIDA-YAGO2-dataset-upadte.tsv` file contains numbers like `11867`. Since the last column is not used during the loading of the dataset, this difference can be ignored.

The encoding problem is very important. Thanks for this hint.
I will check whether we can simply use the wikipedia URIs instead of the titles.

Cheers,
Michael

**Comment by chabmed** [comment]
Hi Michael,
I fixed the problem just with deleting the "http://en.wikipedia.org/wiki/" from AIDA-YAGO2-dataset.tsv
and replacing 
uris = WikipediaHelper.generateUriSet(line[ANNOTATION_TITLE_INDEX]);
with 
uris = WikipediaHelper.generateUriSet(line[ANNOTATION_URI_INDEX]);
Thank you,
Mohamed

**Comment by MichaelRoeder** [comment]
Hi Mohamed,

thanks for this solution. I will implement it in a similar way.

Cheers,
Michael

**Comment by MichaelRoeder** [comment]
Fixed with the release of [v1.2.3](https://github.com/AKSW/gerbil/releases/tag/v1.2.3)
