### ISSUE TITLE
FREME does not work

### ISSUE THREAD

**Issue by RicardoUsbeck** [AKSW/gerbil#125]
Currently it returns always 0.

**Comment by MichaelRoeder** [comment]
It was observed for a D2KB experiment: http://gerbil.aksw.org/gerbil/experiment?id=201604050003

It can be assumed that the response does not fit our NIF interface any more.

**Comment by TortugaAttack** [comment]
OKay. 
I am not sure right now, what exactly turns out 0. 
I've done the SimpleRunTest with FREME and the OKE 2015 Task 1 example set and it results in this: 

> 2016-06-16 14:52:20,043 [pool-1-thread-1] INFO [org.aksw.gerbil.database.SimpleLoggingDAO4Debugging] - <Setting result of task 0 to ExperimentTaskResult(state=0,micF1=0.6956521739130435,micPrecision=0.7272727272727273,micRecall=0.6666666666666666,macF1=0.634920634920635,macPrecision=0.6666666666666666,macRecall=0.6111111111111112,errors=0,16=0.3333333333333333,21=0.0,12=0.7272727272727273,14=0.3333333333333333,26=0.8888888888888888,10=0.9444444444444445,20=649.0,18=0.0,19=0.0,13=0.8888888888888888,15=0.3333333333333333,23=0.9444444444444445,17=0.0,11=0.7999999999999999,9=0.6666666666666666,24=0.9444444444444445,27=0.8888888888888888,22=0.9444444444444445,25=0.8888888888888888,8=0.7666666666666666)>
2016-06-16 14:52:20,043 [pool-1-thread-1] INFO [org.aksw.gerbil.execute.ExperimentTask] - <Task Finished eTConfig("FREME NER","OKE 2015 Task 1 example set","D2KB","STRONG_ENTITY_MATCH")>
2016-06-16 14:52:20,044 [pool-1-thread-1] INFO [org.aksw.simba.topicmodeling.concurrent.reporter.LogReporter] - <Task=ExperimentTask("eTConfig("FREME NER","OKE 2015 Task 1 example set","D2KB","STRONG_ENTITY_MATCH")")	state=TERMINATED	progress=100.0% of dataset>

**Comment by TortugaAttack** [comment]
Well it does work again. So I will close the issue now.

**Comment by MichaelRoeder** [comment]
You are right, it is working. http://w3id.org/gerbil/experiment?id=201606160005
