### ISSUE TITLE
[QA] Add more inline help to config screen

### ISSUE THREAD

**Issue by RicardoUsbeck** [AKSW/gerbil#126]
Please add more hints explaining the terminology in the configuration screen for both deployments.

**Comment by MichaelRoeder** [comment]
Please add a list of hints you would like to have to clarify what should be explained in more detail.

**Comment by RicardoUsbeck** [comment]
I put a mock here. https://docs.google.com/drawings/d/1bXU5IhwXiILcmXukxTUza0jTGLGr8SGtuSVmkGgKn7s/edit?usp=sharing Activate those hints either via hovering or insert a small blue question mark icon next to the dropdown menues.

**Comment by TortugaAttack** [comment]
Wouldn't the question marks make more sense next to the Title (Experiment Type, System, Dataset) instead of next to the Drop Down? 
Not that this is not easily changeable, but i would suspect help more next to the titles. 

Further more, is a tooltip enough or should it be more like a good looking popup?

**Comment by MichaelRoeder** [comment]
A question mark next to the title is a good idea. A tooltip that appears while hovering the question mark is fine.

just my two cents :wink:

**Comment by RicardoUsbeck** [comment]
I agree with Micha. The mock-up was done in a rush. Could you please provide a screenshot of what is implemented and close this ticket?

**Comment by TortugaAttack** [comment]
![gerbil-tooltip](https://cloud.githubusercontent.com/assets/5443313/19963395/7aab9cf6-a1bc-11e6-91f6-6e460a405429.png)
