### ISSUE TITLE
methods in SameAsRetrieverUtils make experiments much slower

### ISSUE THREAD

**Issue by chrishokamp** [AKSW/gerbil#130]
Hi, first off thanks for this great project! 

I was wondering what was taking my experiments so long to finish, so I dug around a bit and found that the calls to `SameAsRetrieverUtils.addSameURIsToMarkings` and `SameAsRetrieverUtils.addSameURIsToMeanings` [here](https://github.com/AKSW/gerbil/blob/master/src/main/java/org/aksw/gerbil/dataset/AbstractDatasetConfiguration.java#L73-L83) and [here](https://github.com/AKSW/gerbil/blob/master/src/main/java/org/aksw/gerbil/execute/ExperimentTask.java#L219-L224) were responsible for almost all of the time that an experiment uses. For D2KB with DBpedia Spotlight and the Spotlight dataset, these two methods take over 95% of the time used by the experiment, adding more than 40 minutes. My question is how necessary they are, and why they take so long? Is there an easy way to make them faster? (for now I just commented out those lines)

**Comment by MichaelRoeder** [comment]
Hi Chris Hokamp,

thanks for using GERBIL :)

Since the version 1.2 GERBIL is build upon a new benchmarking core that is based on [URI matching](https://github.com/AKSW/gerbil/wiki/URI-matching) and the methods you are mentioning belong to [the retrieval of URI sets](https://github.com/AKSW/gerbil/wiki/URI-matching#uri-sets) that is part of this matching. The long runtime you are describing is a known drawback that is listed in the release description (e.g., [v1.2.3](https://github.com/AKSW/gerbil/releases/tag/v1.2.3)). A detailed description of the URI matching and its advantages can be found [here](http://svn.aksw.org/papers/2016/ISWC_Gerbil_Update/public.pdf).

However, you should encounter this long runtime only once. After that, GERBIL should have generated a cache file containing the retrieved information. During the next days, it should simply stick to this file without retrieving the needed information from the web.

The check whether entities are still valid and the retrieval of additional URIs for a given entity can be turned off by commenting out the lines inside the [entity_checking.properties](https://github.com/AKSW/gerbil/blob/master/src/main/properties/entity_checking.properties#L11-L34) and the [gerbil.properties](https://github.com/AKSW/gerbil/blob/master/src/main/properties/gerbil.properties#L76-L83) files that are defining the namespaces for which these operations should be done.

Does this answer your questions?

Cheers,
Michael Röder

**Comment by chrishokamp** [comment]
Hi Michael, 

Yes that's exactly the info I was looking for, thank you very much for the quick and detailed response!!

Cheers,
Chris
