### ISSUE TITLE
Not able to get any datasets with gerbil tag

### ISSUE THREAD

**Issue by constanr** [AKSW/gerbil#85]
When running start.sh, it can't get the datasets with the gerbil tag form DataHubIO:

GET request for "http://datahub.io/api/1/rest/tag/gerbil" resulted in 404 (Not Found); invoking error handler

**Comment by MichaelRoeder** [comment]
Hi Constantino Román Gómez,

this warning is printed because GERBIL can't find any datasets on DataHubIO that can be used.

At the moment no dataset on DataHub is marked as usable by GERBIL because they are 1) no NIF datasets that could be used for one of the experiments or 2) Datasets that are already part of GERBIL and can be loaded locally.

Thus, this warning can be ignored. I added a hint to the wiki.

Best regards,
Michael
